# Generated by Django 5.0.1 on 2024-01-27 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, unique=True)),
                ('director', models.CharField(max_length=200)),
                ('year', models.CharField(max_length=200)),
                ('geners', models.CharField(max_length=200)),
                ('poster', models.ImageField(blank=True, default='default.jpg', upload_to='images')),
                ('actors', models.CharField(max_length=200)),
                ('run_time', models.PositiveIntegerField()),
                ('description', models.CharField(max_length=200, null=True)),
                ('writers', models.CharField(max_length=200)),
                ('language', models.CharField(max_length=200)),
            ],
        ),
    ]
